# Generated by Django 5.2.8 on 2025-11-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_diaryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='review',
        ),
    ]
